### ISSUE TITLE
missing jpgs

### ISSUE THREAD

**Issue by npalardy** [JuliaTruchsess/PopupMenuJT#1]
add the PNG/JPG images to the repository as well 
the Xojo Image does not bring the actual source image with it

FullPath = /Users/Julia/Projects & Docs/PDI/Lab/Xojo Stuff/PopupMenuJT/Images/checkmark.png

**Comment by npalardy** [comment]
Are needs to be added as well

		FullPath = /Users/Julia/Projects & Docs/PDI/Lab/Xojo Stuff/PopupMenuJT/Images/Aria.JPG

**Comment by JuliaTruchsess** [comment]
Added image source files to Images folder
